local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/sdhdbxub/sdhdbxub/main/Wh7Wa8Tb"))()
local window = library:new("Slience X 光 欢迎")

local creds = window:Tab("看",'7734068321')

local bin = creds:section("玩家信息",true)

    bin:Label("你的用户名:"..game.Players.LocalPlayer.Character.Name)
    bin:Label("你的注入器:"..identifyexecutor())
    
    local bin = creds:section("关于的脚本和作者的信息",true)
    bin:Label("借的UI")
    bin:Label("沉默 and 光")
    bin:Label("模式脚本")
    bin:Label("版本Version:2.0Remake Beta")
    
local credits = creds:section("关闭",true)

credits:Toggle("脚本框架变小一点", "", false, function(state)
        if state then
        game:GetService("CoreGui")["frosty"].Main.Style = "DropShadow"
        else
            game:GetService("CoreGui")["frosty"].Main.Style = "Custom"
        end
    end)
    credits:Button("关闭脚本",function()
        game:GetService("CoreGui")["frosty"]:Destroy()
    end)
local creds = window:Tab("复制大群小群系列",'7734068321')

local credits = creds:section("SL",true)
    credits:Button("复制",function()
    setclipboard("https:wc")
end)

local creds = window:Tab("MODE",'7734068321')

local credits = creds:section("MODE",true)
    credits:Button("硬核模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/JevilOhio/Doors-Hardcore-noonie-ver-/main/Doors%20Hardcore%20(noonie)"))()
end)
    credits:Button("硬核重置",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/-v6/main/v6"))()
end)
    credits:Button("糟糕的硬核模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/bad-hardcore-/main/badharhcore"))()
end)
    credits:Button("无尽模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/symmetrical-octo-umbrella/main/ff"))()
end)
    credits:Button("碎片模式",function()
    loadstring(game:HttpGet("https://glot.io/snippets/gpw1ypnl5o/raw/main.lua"))()
end)
    credits:Button("生日模式",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/BirthdayModeDOORS/main/BirthdayModeScript'))()
end)
    credits:Button("困难模式",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/HardcoreScriptDOORS/main/HardcoreModeScript'))()
end)
    credits:Button("朦胧模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/CREATE-HAZYMODE-IN-GITHUB/Create-Hazy-Mode/GITHUB%20WORKLINK%20HAZYMPDE.lua"))()
end)
    credits:Button("恐惧模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/cool59572/freestuff/main/Mods/FearMode.lua"))()
end)
    credits:Button("单人恐惧",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/cool59572/freestuff/main/Fear_mode_multiplayer.lua"))()
end)
    credits:Button("巨魔模式",function()
    loadstring(game:HttpGet("https://glot.io/snippets/gotfeffesc/raw/main.lua"))()
end)
    credits:Button("极端模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Moonsec-Extreme-mode/main/Extreme%20Mode.txt"))()
end)
    credits:Button("HM模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/anmoc/main/hamod"))()
end)
    credits:Button("福瑞模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/furry/main/furry"))()
end)
    credits:Button("噩梦模式",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/Drop56796/HARDCORE-FIXED-MODE-IN-GITHUB/HARDCORE-MODE-FIXED-IN-GITHUB/THE%20HARDCORE%20MODE%20V2.5%20FIXED%20MAKE%20BY%20IN%20GITHUB.lua"),true))()
end)
    credits:Button("疯狂模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/thefigureblack/doors/main/insanemodev5.lua"))()
end)
    credits:Button("不可能模式",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Ukazix/impossible-mode/main/Protected_79.lua.txt'))()
end)
    credits:Button("Noah Dark Mode V1",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Noah-Dark/Noah-Dark-Mode-Script-V1/Noah%20Dark.lua"))()
end)
    credits:Button("Insanity Fog Mode v1.4",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Insanity-Fog-Mode-v1.4/Insanity-Fog-Mode-v1.4-Script/Insanity%20Fog%20Mode%20v1.4%20Script.lua"))()
end)
    credits:Button("MSHUB v4.4.2",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/mstudio45/MSDOORS/main/MSHUB_Loader.lua"),true))()
end)
    credits:Button("slience Script old",function()
    setclipboard("https://raw.githubusercontent.com/Drop56796/slience-Script-Remake/Script-Remake/Remake%20Script.lua")
end)
    credits:Button("最强汉化",function()
    loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\54\53\84\119\84\56\106\97"))()
end)

local creds = window:Tab("道具",'7734068321')

local credits = creds:section("道具AND",true)
    credits:Button("吸铁屎",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/MrNeRD0/Doors-Hack/main/MagnetByNerd.lua"))()
end)
    credits:Button("枪",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ZepsyyCodesLUA/Utilities/main/DOORSFpsGun.lua"))()
end)
    credits:Button("手电筒",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/K0t1n/Public/main/Normal%20Flashlight"))()
end)
    credits:Button("拆掉墙",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/YCGN6bnD"))()
end)
    credits:Button("拆掉假门",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/ZcNPGJfQ"))()
end)
    credits:Button("删掉门的框架",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/4m2Nw1Kr"))()
end)
    credits:Button("走的很快",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/rqA4YPzi", true))()
end)
    credits:Button("走的贼慢",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/HFLkawSE", true))()
end)
    credits:Button("屏幕全亮",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/4LDKiJ5a"))()
end)
    credits:Button("给屏幕加点亮度",function()
    loadstring(game:HttpGet('https://pastebin.com/raw/CbRsLfts'))()
end)
credits:Button("类似于上帝模式但没上帝好",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/BaFjFuCk"))()
end)
credits:Button("没有火焰，seek预测…",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/kXanyBLY"))()
end)

local creds = window:Tab("复制QQ号:slience 和光",'7734068321')

local credits = creds:section("QQ",true)
    credits:Button("slience",function()
    setclipboard("3756646428")
end)
    credits:Button("光",function()
    setclipboard("3791422492")
end)

